-- 1. Show advanced options
EXEC sp_configure 'show advanced options', 1;
RECONFIGURE;

-- 2. Enable OLE Automation Procedures
EXEC sp_configure 'Ole Automation Procedures', 1;
RECONFIGURE;


USE [master];
RESTORE DATABASE [AdventureWorks2019]
FROM DISK = N'C:\MSSQL\Backup\AdventureWorks2019.bak'
WITH FILE = 1
   , MOVE N'AdventureWorks2019'
   , MOVE N'AdventureWorks2019_log'
     TO N'C:\MSSQL\Log\AdventureWorks2019_log.ldf'
   , NOUNLOAD
   , REPLACE
   , STATS = 1;
GO

/*
Example 1: 

    Export and import all data from SQL Instance 'Inst1.docker.internal,1433':
        1. From Database AdventureWorks2022 Schemas: 'HumanResources, Production, Purchasing, Sales'
        2. Matching Table Name patterns: 'Product*, *Address, *Tax*, Employee*, Work*'
    Except for:
        1. Any Table Name in any Schema that ends with 'History' or 'Model'
        2. Any Column Name 'LargePhoto'
        3. Any Column with data type xml
        4. Any Identity Columns
    Into SQL Instance 'Inst2.docker.internal,1433' Database 'AdventureWorks2022_Clone'
    using SQL Authentication (Powershell will promt for User name and password)
    Columns inside all output csv files will be delimited with: '^|^'
    Rows inside all output csv files will be delimited with: '~~~' + newline 
    
    All PowerShell/XmlFormat files will be created by this SP in @OutputDirectoryPsXml (C:\MSSQL\Backup\BCP\ as visible by SQL Server)
    All csv exports generated by running the Powershell Export in step 2 will land in @OutputDirectoryCsv 
    (D:\DOCKER_SHARE\Windows\BackupCommon\BCP\ as visible by machine where PowerShell is run)
    If PowerShell is to be run from a client other than SQL Server then for easiest management,
    to make both the SP and PowerShell operate on the same directory map them together or use a common network share accessible to both
*/

USE [AdventureWorks2022]
GO

DECLARE

  @InstanceNameSrc                    NVARCHAR(128)     = N'Inst1.docker.internal,1433'
, @InstanceNameTgt                    NVARCHAR(128)     = N'Inst2.docker.internal,1433'
, @SqlAuthentication                  BIT               = 1
, @DbNameSrc                          SYSNAME           = N'AdventureWorks2022'
, @DbNameTgt                          SYSNAME           = N'AdventureWorks2022_Clone'
, @OutputDirectoryPsXml               NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @OutputDirectoryCsv                 NVARCHAR(MAX)     = N'D:\DOCKER_SHARE\Windows\BackupCommon\BCP\'                                                        
, @SchemaNames                        NVARCHAR(MAX)     = N'HumanResources, Production, Purchasing, Sales'
, @TableNames                         NVARCHAR(MAX)     = N'Product*, *Address, *Tax*, Employee*, Work*'
, @SchemaNamesExpt                    NVARCHAR(MAX)     = N'*'
, @TableNamesExpt                     NVARCHAR(MAX)     = N'*History, *Model'
, @ColumnNamesExpt                    NVARCHAR(MAX)     = N'LargePhoto'
, @DataTypesExpt                      NVARCHAR(MAX)     = N'xml'
, @DelimBcpOutputField                VARCHAR(3)        = '^|^'
, @DelimBcpOutputRow                  VARCHAR(16)       = '~~~'
, @ExportIdentityCols                 BIT               = 0
, @ExportColumnHeaders                BIT               = 1

EXEC [dbo].[sp_BcpRunner]
                                   @InstanceNameSrc         = @InstanceNameSrc     
                                 , @InstanceNameTgt         = @InstanceNameTgt     
                                 , @SqlAuthentication       = @SqlAuthentication    
                                 , @DbNameSrc               = @DbNameSrc           
                                 , @DbNameTgt               = @DbNameTgt           
                                 , @OutputDirectoryPsXml    = @OutputDirectoryPsXml
                                 , @OutputDirectoryCsv      = @OutputDirectoryCsv  
                                 , @SchemaNames             = @SchemaNames         
                                 , @TableNames              = @TableNames          
                                 , @SchemaNamesExpt         = @SchemaNamesExpt     
                                 , @TableNamesExpt          = @TableNamesExpt      
                                 , @ColumnNamesExpt         = @ColumnNamesExpt     
                                 , @DataTypesExpt           = @DataTypesExpt
                                 , @DelimBcpOutputField     = @DelimBcpOutputField
                                 , @DelimBcpOutputRow       = @DelimBcpOutputRow
                                 , @ExportIdentityCols      = @ExportIdentityCols
                                 , @ExportColumnHeaders     = @ExportColumnHeaders;
/*
Example 2: 

    Export and import all data from Inst2 to Inst1:
        1. From Database AdventureWorksDW2022 Schema: 'dbo'
        2. From All Tables
    Except for:
        1. Any Table Name beginning with 'Fact*' in Schema 'dbo'
        2. Any Column Name beginning with 'Arabic*'

    Into SQL Instance 'Inst1' Database 'AdventureWorksDW2022_Clone'
    using Trusted Windows Authentication (no promt for User name or password)
    Columns inside all output csv files will be delimited with: '^_^'
    Rows inside all output csv files will be delimited with: '~~~' + newline 
    
    All PowerShell/XmlFormat files will be created by this SP in @OutputDirectoryPsXml (C:\MSSQL\Backup\BCP\ as visible by SQL Server)
    All csv exports generated by running the Powershell Export in step 2 will land in @OutputDirectoryCsv 
    (C:\MSSQL\Backup\BCP\ as visible by machine where PowerShell is run)
    If PowerShell is to be run from a client other than SQL Server then for easiest management,
    to make both the SP and PowerShell operate on the same directory map them together or use a common network share accessible to both
*/

USE [AdventureWorksDW2022]
GO

DECLARE

  @InstanceNameSrc                    NVARCHAR(128)     = N'Inst2,1433'
, @InstanceNameTgt                    NVARCHAR(128)     = N'Inst1,1433'
, @SqlAuthentication                  BIT               = 0
, @DbNameSrc                          SYSNAME           = N'AdventureWorksDW2022'
, @DbNameTgt                          SYSNAME           = N'AdventureWorksDW2022_Clone'
, @OutputDirectoryPsXml               NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @OutputDirectoryCsv                 NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @SchemaNames                        NVARCHAR(MAX)     = N'dbo'
, @TableNames                         NVARCHAR(MAX)     = N'*'
, @SchemaNamesExpt                    NVARCHAR(MAX)     = N'dbo'  
, @TableNamesExpt                     NVARCHAR(MAX)     = N'Fact*'
, @ColumnNamesExpt                    NVARCHAR(MAX)     = N'Arabic*'
, @DelimBcpOutputField                VARCHAR(3)        = '^_^'
, @DelimBcpOutputRow                  VARCHAR(16)       = '~~~'
, @ExportIdentityCols                 BIT               = 1
, @ExportColumnHeaders                BIT               = 1

EXEC [dbo].[sp_BcpRunner]
                                   @InstanceNameSrc         = @InstanceNameSrc     
                                 , @InstanceNameTgt         = @InstanceNameTgt     
                                 , @SqlAuthentication       = @SqlAuthentication    
                                 , @DbNameSrc               = @DbNameSrc           
                                 , @DbNameTgt               = @DbNameTgt           
                                 , @OutputDirectoryPsXml    = @OutputDirectoryPsXml
                                 , @OutputDirectoryCsv      = @OutputDirectoryCsv  
                                 , @SchemaNames             = @SchemaNames         
                                 , @TableNames              = @TableNames
                                 , @SchemaNamesExpt         = @SchemaNamesExpt
                                 , @TableNamesExpt          = @TableNamesExpt 
                                 , @ColumnNamesExpt         = @ColumnNamesExpt 
                                 , @DelimBcpOutputField     = @DelimBcpOutputField
                                 , @DelimBcpOutputRow       = @DelimBcpOutputRow
                                 , @ExportIdentityCols      = @ExportIdentityCols
                                 , @ExportColumnHeaders     = @ExportColumnHeaders
/*
Example 3: 

    Export and import all data from SQL Instance 'Inst2.docker.internal,1433':
    using SQL Authentication (Powershell will promt for User name and password)
        1. From Database AdventureWorks2022 Schema: 'Sales'
        2. Tables: 'SalesOrderHeader, SalesOrderDetail, SalesPerson'
    Except for:
        1. Any Columns with datatype 'uniqueidentifier'
        2. Any Identity Columns
    Into SNOWFLAKE Instance where SnowflakeImport.sql will need to be executed to script out the import steps
    Snowflake's target database is specified as 'AdventureWorks2022_Snow'
    Columns inside all output csv files will be delimited with: '^|^'
    Rows inside all output csv files will be delimited with: '~~~' + newline 

    All PowerShell/XmlFormat files will be created by this SP in @OutputDirectoryPsXml (C:\MSSQL\Backup\BCP\ as visible by SQL Server)
    All csv exports generated by running the Powershell Export in step 2 will land in @OutputDirectoryCsv 
    (D:\DOCKER_SHARE\Windows\BackupCommon\BCP\ as visible by machine where PowerShell is run)
    If PowerShell is to be run from a client other than SQL Server then for easiest management,
    to make both the SP and PowerShell operate on the same directory map them together or use a common network share accessible to both
*/

USE [AdventureWorks2022]
GO

DECLARE

  @InstanceNameSrc                    NVARCHAR(128)     = N'Inst2.docker.internal,1433'
, @SqlAuthentication                  BIT               = 1
, @DbNameSrc                          SYSNAME           = N'AdventureWorks2022'
, @DbNameTgt                          SYSNAME           = N'AdventureWorks2022_Snow'
, @OutputDirectoryPsXml               NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @OutputDirectoryCsv                 NVARCHAR(MAX)     = N'D:\DOCKER_SHARE\Windows\BackupCommon\BCP\'                                                        
, @SchemaNames                        NVARCHAR(MAX)     = 'Sales'
, @TableNames                         NVARCHAR(MAX)     = 'SalesOrderHeader, SalesOrderDetail, SalesPerson'
, @DataTypesExpt                      NVARCHAR(MAX)     = N'uniqueidentifier'
, @DelimBcpOutputField                VARCHAR(3)        = '^|^'
, @DelimBcpOutputRow                  VARCHAR(16)       = '~~~'
, @ExportIdentityCols                 BIT               = 0
, @ExportColumnHeaders                BIT               = 1
, @AllowNotNullColumnsAsExceptions    BIT               = 1
, @ImportTarget                       VARCHAR(16)       = 'SNOWFLAKE'

EXEC [dbo].[sp_BcpRunner]
                                   @InstanceNameSrc                 = @InstanceNameSrc   
                                 , @SqlAuthentication               = @SqlAuthentication  
                                 , @DbNameSrc                       = @DbNameSrc           
                                 , @DbNameTgt                       = @DbNameTgt           
                                 , @OutputDirectoryPsXml            = @OutputDirectoryPsXml
                                 , @OutputDirectoryCsv              = @OutputDirectoryCsv  
                                 , @SchemaNames                     = @SchemaNames         
                                 , @TableNames                      = @TableNames            
                                 , @DataTypesExpt                   = @DataTypesExpt
                                 , @DelimBcpOutputField             = @DelimBcpOutputField
                                 , @DelimBcpOutputRow               = @DelimBcpOutputRow
                                 , @ExportIdentityCols              = @ExportIdentityCols
                                 , @ExportColumnHeaders             = @ExportColumnHeaders
                                 , @AllowNotNullColumnsAsExceptions = @AllowNotNullColumnsAsExceptions
                                 , @ImportTarget                    = @ImportTarget
GO

/*
Example 4: 

    Export and import the entire AdventureWorks2025 database from SQL Instance 'Inst3.docker.internal,1433'
    No Exceptions
    Into SQL Instance 'Inst2.docker.internal,1433' Database 'AdventureWorks2025_Clone'
    using SQL Authentication (Powershell will promt for User name and password)
    Columns inside all output csv files will be delimited with: '^|^'
    Rows inside all output csv files will be delimited with: '~~~' + newline 
    
    All PowerShell/XmlFormat files will be created by this SP in @OutputDirectoryPsXml (C:\MSSQL\Backup\BCP\ as visible by SQL Server)
    All csv exports generated by running the Powershell Export in step 2 will land in @OutputDirectoryCsv 
    (D:\DOCKER_SHARE\Windows\BackupCommon\BCP\ as visible by machine where PowerShell is run)
    If PowerShell is to be run from a client other than SQL Server then for easiest management,
    to make both the SP and PowerShell operate on the same directory map them together or use a common network share accessible to both
*/

USE [AdventureWorks2025]
GO

DECLARE

  @InstanceNameSrc                    NVARCHAR(128)     = N'Inst3.docker.internal,1433'
, @InstanceNameTgt                    NVARCHAR(128)     = N'Inst2.docker.internal,1433'
, @SqlAuthentication                  BIT               = 1
, @DbNameSrc                          SYSNAME           = N'AdventureWorks2025'
, @DbNameTgt                          SYSNAME           = N'AdventureWorks2025_Clone'
, @OutputDirectoryPsXml               NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @OutputDirectoryCsv                 NVARCHAR(MAX)     = N'D:\DOCKER_SHARE\Windows\BackupCommon\BCP\'                                                        
, @ExportAllTablesPerDB               BIT               = 1
, @DelimBcpOutputField                VARCHAR(3)        = '^|^'
, @DelimBcpOutputRow                  VARCHAR(16)       = '~~~'
, @ExportIdentityCols                 BIT               = 1
, @ExportColumnHeaders                BIT               = 1
, @ImportTarget                       VARCHAR(16)       = 'SNOWFLAKE'

EXEC [dbo].[sp_BcpRunner]
                                   @InstanceNameSrc         = @InstanceNameSrc     
                                 , @InstanceNameTgt         = @InstanceNameTgt     
                                 , @SqlAuthentication       = @SqlAuthentication    
                                 , @DbNameSrc               = @DbNameSrc           
                                 , @DbNameTgt               = @DbNameTgt           
                                 , @OutputDirectoryPsXml    = @OutputDirectoryPsXml
                                 , @OutputDirectoryCsv      = @OutputDirectoryCsv  
                                 , @ExportAllTablesPerDB    = @ExportAllTablesPerDB
                                 , @DelimBcpOutputField     = @DelimBcpOutputField
                                 , @DelimBcpOutputRow       = @DelimBcpOutputRow
                                 , @ExportIdentityCols      = @ExportIdentityCols
                                 , @ExportColumnHeaders     = @ExportColumnHeaders
                                 , @ImportTarget            = @ImportTarget;

/*
Example 5: 

    Export and import from SQL Instance: 'Inst3.docker.internal,1433'
                         , Database: AdventureWorks2025
                         , Schema: Production
                         , Tables: TransactionHistory, WorkOrder, BillOfMaterials;
    No Exceptions
    Into SQL Instance 'Inst2.docker.internal,1433' Database 'AdventureWorks2025_Clone'
    using SQL Authentication (Powershell will promt for User name and password)
    Columns inside all output csv files will be delimited with: '^|^'
    Rows inside all output csv files will be delimited with: '~~~' + newline 
    
    All PowerShell/XmlFormat files will be created by this SP in @OutputDirectoryPsXml (C:\MSSQL\Backup\BCP\ as visible by SQL Server)
    All csv exports generated by running the Powershell Export in step 2 will land in @OutputDirectoryCsv 
    (D:\DOCKER_SHARE\Windows\BackupCommon\BCP\ as visible by machine where PowerShell is run)
    If PowerShell is to be run from a client other than SQL Server then for easiest management,
    to make both the SP and PowerShell operate on the same directory map them together or use a common network share accessible to both
*/

USE [AdventureWorks2025]
GO

DECLARE

  @InstanceNameSrc                    NVARCHAR(128)     = N'Inst3.docker.internal,1433'
, @InstanceNameTgt                    NVARCHAR(128)     = N'Inst2.docker.internal,1433'
, @SqlAuthentication                  BIT               = 1
, @DbNameSrc                          SYSNAME           = N'AdventureWorks2025'
, @DbNameTgt                          SYSNAME           = N'AdventureWorks2025_Clone'
, @OutputDirectoryPsXml               NVARCHAR(MAX)     = N'C:\MSSQL\Backup\BCP\'
, @OutputDirectoryCsv                 NVARCHAR(MAX)     = N'D:\DOCKER_SHARE\Windows\BackupCommon\BCP\'                                                        
, @SchemaNames                        NVARCHAR(MAX)     = N'Production'
, @TableNames                         NVARCHAR(MAX)     = N'TransactionHistory, WorkOrder, BillOfMaterials'
, @DelimBcpOutputField                VARCHAR(3)        = '^|^'
, @DelimBcpOutputRow                  VARCHAR(16)       = '~~~'
, @ExportIdentityCols                 BIT               = 1
, @ExportColumnHeaders                BIT               = 1

EXEC [dbo].[sp_BcpRunner]
                                   @InstanceNameSrc         = @InstanceNameSrc     
                                 , @InstanceNameTgt         = @InstanceNameTgt     
                                 , @SqlAuthentication       = @SqlAuthentication    
                                 , @DbNameSrc               = @DbNameSrc           
                                 , @DbNameTgt               = @DbNameTgt           
                                 , @OutputDirectoryPsXml    = @OutputDirectoryPsXml
                                 , @OutputDirectoryCsv      = @OutputDirectoryCsv
                                 , @SchemaNames             = @SchemaNames         
                                 , @TableNames              = @TableNames
                                 , @DelimBcpOutputField     = @DelimBcpOutputField
                                 , @DelimBcpOutputRow       = @DelimBcpOutputRow
                                 , @ExportIdentityCols      = @ExportIdentityCols
                                 , @ExportColumnHeaders     = @ExportColumnHeaders;
GO